name: Fetch Gazette Kika

on:
  schedule:
    - cron:  '30 0 * * *'  # JST 09:30 に相当
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET:             ${{ secrets.S3_BUCKET }}
        run: python scripts/fetch_kika.py

      - run: |
          git config user.name  github-actions
          git config user.email github-actions@users.noreply.github.com
          git add data/csv/*.csv
          if ! git diff --cached --quiet; then
            git commit -m "Add daily CSV"
            git push
          fi

